### ISSUE TITLE
Dekart without postgresql

### ISSUE THREAD

**Issue by AdeelK93** [dekart-xyz/dekart#22]
Hi, is there a way to run Dekart (via docker) without postgresql? I don't really need to save any metadata, and I don't want to have to manage a postgres database in order to use Dekart.

Not passing in the postgres environmental variables gets me this error:

> {"level":"fatal","error":"dial tcp 127.0.0.1:5432: connect: connection refused","time":1638744281,"message":"WithInstance"}

I suppose another solution would be to include postgres in the Dockerfile so that one could be available on localhost.

Thank you!

**Comment by delfrrr** [comment]
Hey @AdeelK93  currently it's not possible, you need to Postgres; it is used to store query metadata and map configs so you can return to them later; 

If you could describe you use-case in detail it would help us to consider it for future versions

currently I can offer this docker-compose example with should be easy enough to run on single instance or locally: https://dekart.xyz/docs/self-hosting/docker-compose/

**Comment by delfrrr** [comment]
Heads up: we are considering introduce alternative (fully managed) db option for Dekart which hopefully will make deployment to GCP much cheaper. Stay tuned.

**Comment by AdeelK93** [comment]
Neat! Ease of deployment was really the use case

**Comment by delfrrr** [comment]
Hey so this is a working proposal to use Firebase to store Reports Metadata

<img width="763" alt="Screenshot 2021-12-27 at 08 06 04" src="https://user-images.githubusercontent.com/495642/147444767-18be6938-d264-4738-b624-e8a32c021178.png">

* User Firestore Instead of Postgres
* Stream Query Status using Firestore Real Time Updates instead of sync via in-memory storage

Advantages
* Dekart Server can be scaled up and down on App Engine
* No user sessions lost during deploying/restarting
* GCP Billing will be proportional to number of request and not to time available (cheaper for small number of requests)
